name: default_elixir_ci

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apk add git
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        mix test --color --cover
        mix docs

