name: elixir_ci_hex_publish

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apk add git
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        MIX_ENV=test mix coveralls
        mix docs
    - name: Publish to Hex
      if: github.event.pull_request.merged == true
      run: |
        mix hex.publish --yes

